import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { AuthProvider } from "@/contexts/AuthContext";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "나나랜드 (나만의 나라!)",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`
        ${geistSans.variable} ${geistMono.variable} antialiased
        min-h-screen
        bg-[url('/images/background.png')]
        bg-cover
        bg-center
        bg-fixed
      `}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
